// examples/microfrontend-react-shell-react-vue-app/react-app/src/bootstrap.jsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

const mount = (rootElement, { store }) => {
  const root = ReactDOM.createRoot(rootElement);
  // recieve store from container
  root.render(<App store={store} />);
};

if (import.meta.env.MODE === 'development') {
  // STANDALONE MODE
  const devRoot = document.querySelector('#react_app_root');
  if (devRoot) {
    mount(devRoot, { store: null });
  }
}

export { mount };

// examples/microfrontend/react-shell-react-vue-app/vue-app/src/bootstrap.js
import { createApp } from 'vue';
import './style.css';
import App from './App.vue';

const mount = (rootElement, { store }) => {
  // recieve store from container
  const { results } = store;
  const app = createApp(App, { results });
  app.mount(rootElement);
  return app;
};

if (import.meta.env.MODE === 'development') {
  // STANDALONE MODE
  const vueApp = document.querySelector('#app');
  mount(vueApp, { store: null });
}

export { mount };
